name: gnome-characters
adopt-info: gnome-characters
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

layout:
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs

slots:
  # for GtkApplication registration
  gnome-characters:
    interface: dbus
    bus: session
    name: org.gnome.Characters

apps:
  gnome-characters:
    command: usr/share/org.gnome.Characters/org.gnome.Characters
    extensions: [gnome-3-38]
    plugs:
      - browser-support
      - home
    desktop: usr/share/applications/org.gnome.Characters.desktop
    common-id: org.gnome.Characters.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/org.gnome.Characters:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/gnome-platform/usr/lib:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/org.gnome.Characters/girepository-1.0:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gjs/girepository-1.0:$SNAP/gnome-platform/usr/lib/girepository-1.0:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0

parts:
  gnome-characters:
    source: https://gitlab.gnome.org/GNOME/gnome-characters.git
    source-type: git
    source-branch: gnome-41
    plugin: meson
    meson-parameters: [--buildtype=release, --prefix=/snap/gnome-characters/current/usr]
    meson-version: 0.58.1
    parse-info: [usr/share/metainfo/org.gnome.Characters.appdata.xml]
    organize:
      snap/gnome-characters/current/usr: usr
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
      sed -i -e 's|@GJS@|/usr/bin/gjs|g' src/org.gnome.Characters.in
      sed -i -e 's|@GJS@|/usr/bin/gjs|g' src/org.gnome.Characters.BackgroundService.in
      sed -i.bak -e 's|=@appid@$|=${SNAP}/meta/gui/org.gnome.Characters.svg|g' data/org.gnome.Characters.desktop.in
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.Characters.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      sed -i.bak -e 's|=@bindir@/gnome-characters$|=${SNAP}/usr/share/org.gnome.Characters/org.gnome.Characters|g' data/org.gnome.Characters.desktop.in
      rm -f $SNAPCRAFT_PART_INSTALL/snap/gnome-characters/current/usr/bin/gnome-characters
    build-packages:
      - desktop-file-utils
      - gperf
      - libunistring-dev
